// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "8d81c191171b427c4cc8594727d1afec45f0ca6931fc1308e9eed3039ff8d1f4")
